version: '3.4'

services:
  tfsdeploymentchecker.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_TfsToken
      - ASPNETCORE_TfsUrl
      - ASPNETCORE_AllowUntrustedSslCertificates
      - ASPNETCORE_SystemsOfInterest
      - ASPNETCORE_TeamProjectsAndReleaseIdsPairs
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro