name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore DeploymentChecker.sln
    - name: Build DeploymentChecker.sln
      run: dotnet build --no-restore TfsDeploymentChecker.UI/TfsDeploymentChecker.UI.csproj
    - name: Test TfsDeploymentChecker.BusinessLogic.UnitTests\TfsDeploymentChecker.BusinessLogic.UnitTests.csproj
      run: dotnet test --no-build --verbosity normal
